"""
Divya Foods — Seed Recipe Content
=============================================
Seeds the recipes collection: the original 8 hand-written recipes (migrated
from the old static src/data/recipes.ts) plus a curated batch spanning every
cuisine/category the catalog actually supports. Every recipe's product_tags
are drawn from real product names/tags (see backend/scripts/create_admin.py
for the same direct-pymongo connection pattern) so recipe_service._resolve_products
finds a real, buyable product via the existing product text-search index.

No cheese recipes are included — there are zero cheese products in the
catalog (confirmed via the live /categories and /products endpoints), and
recipes must only be created for products actually sold on the site.

Safe to re-run: admin_bulk_import_recipes skips titles that already exist.

Usage (from the project root):
  cd backend
  python scripts/seed_recipes.py
"""

import os
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))

from pymongo import MongoClient

from app.services import recipe_service


def load_env():
    env_path = Path(__file__).parent.parent / ".env"
    env = {}
    if env_path.exists():
        for line in env_path.read_text(encoding="utf-8").splitlines():
            line = line.strip()
            if line and not line.startswith("#") and "=" in line:
                k, _, v = line.partition("=")
                env[k.strip()] = v.strip()
    return env


ENV = load_env()
# Real process env vars (e.g. injected by `railway run` against production)
# take precedence over the local .env file, so this script can seed either
# the local dev database or production without any code changes.
MONGODB_URL = os.environ.get("MONGODB_URL") or ENV.get("MONGODB_URL", "mongodb://localhost:27017")
DATABASE_NAME = os.environ.get("DATABASE_NAME") or ENV.get("DATABASE_NAME", "divyafoods")


# ─── The 8 original recipes, migrated to the new schema ────────────────────

MIGRATED = [
    dict(
        title="Garlic Butter Salmon", emoji="🧄", cuisine="Continental", category="seafood",
        description="Perfectly seared salmon with a rich garlic butter sauce. Restaurant quality in 15 minutes.",
        ingredients=["2 salmon fillets (200g each)", "3 tbsp butter", "4 cloves garlic (minced)",
                     "1 lemon (juice + zest)", "Fresh dill or parsley", "Salt & black pepper"],
        steps=["Thaw salmon in refrigerator overnight. Pat completely dry with paper towel — moisture prevents a good sear.",
               "Season generously with salt and pepper on both sides.",
               "Heat 1 tbsp butter in a non-stick pan over medium-high heat until foaming.",
               "Place salmon skin-side up. Cook without moving for 4 minutes until a golden crust forms.",
               "Flip. Add remaining butter and minced garlic. Squeeze in lemon juice.",
               "Baste the fish with the pan butter for 3-4 more minutes until cooked through.",
               "Remove when center is just opaque. Rest 1 minute. Garnish with fresh herbs and lemon zest."],
        prep_time_minutes=5, cook_time_minutes=10, difficulty="Easy", servings=2,
        tags=["pan-fry", "quick", "keto"], product_tags=["salmon", "fresh salmon portions"],
        search_keywords=["garlic butter salmon recipe", "pan seared salmon"],
    ),
    dict(
        title="Miso Glazed Salmon", emoji="🍱", cuisine="Japanese", category="grilled",
        description="Japanese-style salmon with a sweet-savory miso glaze. Great for meal prep — marinate ahead.",
        ingredients=["2 salmon fillets", "2 tbsp white miso paste", "1 tbsp mirin", "1 tbsp soy sauce",
                     "1 tsp sugar", "Sesame seeds & spring onion to garnish"],
        steps=["Mix miso paste, mirin, soy sauce, and sugar into a smooth glaze.",
               "Coat salmon fillets with glaze on all sides.",
               "Cover and marinate in refrigerator for 30 minutes (up to 2 hours for deeper flavor).",
               "Preheat oven to 200C or prepare a grill.",
               "Bake for 12-14 mins OR grill flesh-side down for 4 mins, then flip for 3 mins.",
               "The glaze should be slightly caramelized and sticky - watch it doesn't burn.",
               "Serve with steamed Japanese rice. Garnish with sesame seeds and spring onion."],
        prep_time_minutes=35, cook_time_minutes=14, difficulty="Medium", servings=2,
        tags=["japanese", "oven", "grilled"], product_tags=["salmon", "shiro miso paste", "hon mirin"],
        search_keywords=["miso salmon recipe", "japanese salmon"],
    ),
    dict(
        title="Chilli Garlic Prawns", emoji="🌶️", cuisine="Asian", category="seafood",
        description="Fiery stir-fried prawns with garlic and chilli. Ready in under 10 minutes — perfect weeknight dinner.",
        ingredients=["500g prawns (deveined)", "6 cloves garlic (sliced thin)", "2 red chillies (sliced)",
                     "2 tbsp soy sauce", "1 tbsp oyster sauce", "1 tsp sesame oil", "2 tbsp cooking oil",
                     "Spring onion & sesame seeds to garnish"],
        steps=["Thaw prawns, devein if needed, pat completely dry.",
               "Heat oil in a wok or large frying pan on HIGH heat until smoking.",
               "Add garlic and chilli - stir-fry for 30 seconds until fragrant.",
               "Add prawns in a single layer. Cook without stirring for 90 seconds.",
               "Flip the prawns. Add soy sauce and oyster sauce. Toss to coat for 60 seconds.",
               "Drizzle sesame oil. Remove from heat immediately - don't overcook.",
               "Serve over steamed rice. Garnish with spring onion and sesame seeds."],
        prep_time_minutes=5, cook_time_minutes=5, difficulty="Easy", servings=3,
        tags=["stir-fry", "quick", "spicy"], product_tags=["prawns", "vannamei white prawns"],
        search_keywords=["chilli garlic prawns recipe", "spicy prawn stir fry"],
    ),
    dict(
        title="Coconut Prawn Curry", emoji="🍛", cuisine="Indian", category="curry",
        description="Rich, creamy coconut prawn curry with aromatic spices. Best served with steamed basmati rice.",
        ingredients=["500g prawns (deveined)", "1 can (400ml) coconut milk", "2 medium tomatoes (chopped)",
                     "1 large onion (finely chopped)", "4 cloves garlic + 1in ginger (paste)",
                     "1 tsp turmeric, 1 tsp cumin, 2 tsp coriander powder, 1 tsp chilli powder",
                     "2 tbsp oil, salt to taste", "Fresh coriander to garnish"],
        steps=["Thaw prawns and marinate with turmeric and salt for 10 minutes.",
               "Heat oil in a kadai. Fry onions until golden (8-10 mins).",
               "Add garlic-ginger paste. Cook 2 minutes until raw smell goes away.",
               "Add tomatoes, cook until soft and masala comes together (5 mins).",
               "Add cumin, coriander, chilli powder. Stir and cook 2 minutes.",
               "Pour in coconut milk. Simmer 5 minutes on medium heat.",
               "Add prawns. Cook 4-5 minutes - they turn pink and curl when done.",
               "Garnish with fresh coriander. Serve with steamed rice or naan."],
        prep_time_minutes=15, cook_time_minutes=25, difficulty="Medium", servings=4,
        tags=["curry", "indian", "coconut"], product_tags=["prawns", "jumbo tiger prawns"],
        search_keywords=["coconut prawn curry recipe", "indian prawn curry"],
    ),
    dict(
        title="Crispy Calamari", emoji="🍤", cuisine="Italian", category="snack",
        description="Golden-crisp calamari rings with a light seasoned coating. Perfect party starter.",
        ingredients=["400g squid rings", "1 cup all-purpose flour", "1 tsp salt, 1 tsp black pepper",
                     "1 tsp paprika / chilli powder", "Oil for deep frying", "Lemon wedges to serve",
                     "Mayonnaise or tartar sauce for dipping"],
        steps=["Thaw squid rings. Pat completely dry - moisture makes them steam instead of fry.",
               "Mix flour, salt, pepper, and paprika in a shallow bowl.",
               "Heat oil in a deep pan to 180C (test: a small piece should sizzle immediately).",
               "Coat squid rings in flour mix, shaking off all excess.",
               "Fry in small batches for 60-90 seconds only. Do not overcrowd the pan.",
               "Drain immediately on paper towels.",
               "Season with extra salt while hot. Serve immediately with lemon and dipping sauce."],
        prep_time_minutes=10, cook_time_minutes=10, difficulty="Easy", servings=4,
        tags=["deep-fry", "starter", "party"], product_tags=["squid rings", "calamari rings"],
        search_keywords=["crispy calamari recipe", "fried squid rings"],
    ),
    dict(
        title="Pan-Seared Tuna Steak", emoji="🐠", cuisine="Japanese", category="seafood",
        description="Seared tuna steak with a soy-ginger glaze. Slightly rare in the center — restaurant elegance at home.",
        ingredients=["2 tuna steaks (200g each, 2cm thick)", "2 tbsp soy sauce", "1 tbsp sesame oil",
                     "1 tbsp ginger (grated)", "1 clove garlic (minced)", "1 tsp honey",
                     "White sesame seeds, spring onion to serve"],
        steps=["Thaw tuna steaks. Pat completely dry.",
               "Mix soy sauce, sesame oil, ginger, garlic, and honey into a marinade.",
               "Marinate tuna for 10 minutes (not longer - acid starts to \"cook\" the fish).",
               "Heat a cast-iron skillet or heavy pan on HIGH until smoking hot.",
               "Add a touch of oil. Sear tuna 1-2 minutes per side - it should be golden outside, pink inside.",
               "Remove from heat. Rest 1 minute.",
               "Slice against the grain. Garnish with sesame seeds and spring onion."],
        prep_time_minutes=10, cook_time_minutes=4, difficulty="Easy", servings=2,
        tags=["seared", "keto", "japanese"], product_tags=["tuna steak", "bluefin tuna"],
        search_keywords=["seared tuna steak recipe", "soy ginger tuna"],
    ),
    dict(
        title="Butter Garlic Crab", emoji="🦀", cuisine="Asian", category="seafood",
        description="Indulgent butter garlic crab with a rich sauce. A Divya Foods signature recipe.",
        ingredients=["1 whole crab (500-700g), cleaned and halved", "4 tbsp butter", "8 cloves garlic (minced)",
                     "2 tbsp soy sauce", "1 tbsp oyster sauce", "1 tsp sugar",
                     "Fresh coriander & red chilli to garnish"],
        steps=["Steam or boil the crab for 12-15 minutes until bright orange all over. Set aside.",
               "Melt butter in a large wok or pan over medium heat.",
               "Add minced garlic - cook 2 minutes until golden and fragrant.",
               "Add soy sauce, oyster sauce, and sugar. Stir to combine.",
               "Add the cooked crab pieces. Toss to coat well in the sauce for 3-4 minutes.",
               "Taste and adjust seasoning - add more butter for richness.",
               "Serve immediately garnished with coriander and sliced red chilli."],
        prep_time_minutes=15, cook_time_minutes=20, difficulty="Medium", servings=2,
        tags=["butter", "garlic", "premium"], product_tags=["whole rock crab", "mud crab"],
        search_keywords=["butter garlic crab recipe", "whole crab recipe"],
    ),
    dict(
        title="Grilled Butter Lobster", emoji="🦞", cuisine="Continental", category="grilled",
        description="Split lobster grilled with herb butter — an impressive centerpiece for special occasions.",
        ingredients=["1 whole lobster (split in half lengthwise)", "4 tbsp butter (softened)",
                     "3 cloves garlic (minced)", "1 tbsp fresh parsley (chopped)", "1 tsp paprika",
                     "Juice of 1 lemon", "Salt & black pepper"],
        steps=["Thaw lobster in refrigerator overnight. Split lengthwise with a sharp knife.",
               "Mix butter, garlic, parsley, paprika, salt, and pepper into herb butter.",
               "Generously brush herb butter over exposed lobster flesh.",
               "Preheat grill to high. Place lobster flesh-side down for 4-5 minutes.",
               "Flip. Brush more herb butter. Grill shell-side down for 4-5 minutes more.",
               "Lobster is done when flesh turns white/opaque and shell turns bright red.",
               "Squeeze fresh lemon over. Serve with crusty bread and remaining herb butter."],
        prep_time_minutes=10, cook_time_minutes=10, difficulty="Medium", servings=2,
        tags=["grilled", "premium", "date-night"], product_tags=["lobster tail", "canadian lobster tail"],
        search_keywords=["grilled lobster recipe", "herb butter lobster"],
    ),
]


# ─── New curated batch, spanning cuisines/categories not yet covered ────────

NEW_BATCH = [
    dict(
        title="Teriyaki Glazed Salmon", emoji="🍶", cuisine="Japanese", category="seafood",
        description="Salmon fillets basted in a sticky-sweet Kikkoman teriyaki glaze until caramelized.",
        ingredients=["2 salmon fillets", "4 tbsp Kikkoman teriyaki marinade & sauce", "1 tsp vegetable oil",
                     "1 tsp sesame seeds", "1 spring onion, sliced"],
        steps=["Pat salmon dry and season lightly with salt.",
               "Heat oil in a non-stick pan over medium-high heat, place salmon skin-side down.",
               "Cook 4 minutes until crisp, then flip.",
               "Pour teriyaki sauce over the salmon, reduce heat to medium.",
               "Baste continuously for 4-5 minutes until the glaze thickens and coats the fillets.",
               "Garnish with sesame seeds and spring onion. Serve over steamed rice."],
        prep_time_minutes=5, cook_time_minutes=10, difficulty="Easy", servings=2,
        tags=["japanese", "quick", "glazed"], product_tags=["salmon", "kikkoman teriyaki sauce"],
        search_keywords=["teriyaki salmon recipe", "kikkoman salmon"],
    ),
    dict(
        title="Salmon Poke Bowl", emoji="🥢", cuisine="Japanese", category="seafood",
        description="Sashimi-grade salmon cubes over sushi rice with a soy-sesame dressing — a cool, no-cook lunch bowl.",
        ingredients=["200g sashimi grade salmon block, cubed", "2 cups cooked sushi rice",
                     "2 tbsp soy sauce", "1 tsp sesame oil", "1 sheet nori, sliced into strips",
                     "1/2 avocado, sliced", "Sesame seeds"],
        steps=["Cook sushi rice and let it cool to room temperature.",
               "Cube the sashimi-grade salmon into bite-size pieces.",
               "Whisk soy sauce and sesame oil, toss gently with the salmon.",
               "Divide rice between two bowls.",
               "Top with dressed salmon, avocado slices, and nori strips.",
               "Finish with sesame seeds and serve immediately."],
        prep_time_minutes=15, cook_time_minutes=0, difficulty="Easy", servings=2,
        tags=["no-cook", "japanese", "healthy"], product_tags=["sashimi grade salmon block", "nori"],
        search_keywords=["salmon poke bowl recipe", "sashimi salmon bowl"],
    ),
    dict(
        title="Smoked Salmon Blinis", emoji="🥂", cuisine="Continental", category="snack",
        description="Classic canape of smoked salmon on soft blinis with a dollop of crème fraîche — an easy premium starter.",
        ingredients=["150g smoked salmon portions, sliced thin", "12 mini blinis or crackers",
                     "4 tbsp crème fraîche or sour cream", "1 tbsp fresh dill, chopped", "Lemon wedges"],
        steps=["Warm the blinis briefly if using fresh ones.",
               "Top each blini with a small spoon of crème fraîche.",
               "Drape a slice of smoked salmon on top.",
               "Garnish with chopped dill and a squeeze of lemon.",
               "Arrange on a platter and serve immediately."],
        prep_time_minutes=15, cook_time_minutes=0, difficulty="Easy", servings=4,
        tags=["starter", "party", "no-cook"], product_tags=["smoked salmon portions", "smoked salmon fillet"],
        search_keywords=["smoked salmon blinis recipe", "salmon canape"],
    ),
    dict(
        title="Norwegian Salmon Chowder", emoji="🍲", cuisine="Continental", category="soup",
        description="A creamy, comforting chowder built around flaked Norwegian salmon, potatoes and sweetcorn.",
        ingredients=["300g Norwegian Atlantic salmon fillet", "2 potatoes, diced", "1 onion, chopped",
                     "1 cup sweetcorn", "2 cups fish or vegetable stock", "1 cup cream",
                     "2 tbsp butter", "Salt & pepper", "Fresh parsley to garnish"],
        steps=["Melt butter in a pot, saute onion until soft.",
               "Add potatoes and stock, simmer 12 minutes until potatoes are tender.",
               "Cut salmon into chunks and add to the pot along with sweetcorn.",
               "Simmer gently 6-8 minutes until salmon is just cooked through.",
               "Stir in cream, season with salt and pepper, warm through without boiling.",
               "Ladle into bowls and garnish with parsley."],
        prep_time_minutes=10, cook_time_minutes=25, difficulty="Medium", servings=4,
        tags=["soup", "comfort-food", "creamy"], product_tags=["norwegian atlantic salmon fillet"],
        search_keywords=["salmon chowder recipe", "norwegian salmon soup"],
    ),
    dict(
        title="Basa Fish Curry", emoji="🍛", cuisine="Indian", category="curry",
        description="Mild basa fillets simmered in a tangy tomato-onion curry — a quick, boneless weeknight fish curry.",
        ingredients=["400g Indian basa fish fillet, cut into pieces", "2 tomatoes, pureed",
                     "1 onion, finely chopped", "1 tbsp ginger-garlic paste",
                     "1 tsp turmeric, 1 tsp red chilli powder, 1 tsp coriander powder",
                     "2 tbsp mustard oil or cooking oil", "Curry leaves", "Salt to taste"],
        steps=["Marinate basa pieces with turmeric and salt for 10 minutes.",
               "Heat oil, splutter curry leaves, then saute onion until golden.",
               "Add ginger-garlic paste, cook 2 minutes.",
               "Add tomato puree and dry spices, cook until oil separates (6-8 mins).",
               "Add a splash of water to loosen the gravy, bring to a simmer.",
               "Gently slide in the basa pieces, cover and cook 6-7 minutes without stirring hard.",
               "Serve hot with steamed rice."],
        prep_time_minutes=15, cook_time_minutes=20, difficulty="Medium", servings=4,
        tags=["curry", "indian", "boneless"], product_tags=["indian basa fish fillet", "basa"],
        search_keywords=["basa fish curry recipe", "boneless fish curry"],
    ),
    dict(
        title="Crispy Fried Basa", emoji="🐟", cuisine="Indian", category="snack",
        description="Basa fillets marinated in spices and shallow-fried until golden and crisp — a classic Indian fish fry.",
        ingredients=["400g Vietnamese basa fish fillet", "1 tbsp ginger-garlic paste",
                     "1 tsp turmeric, 1 tsp red chilli powder", "1 tbsp semolina (rava)",
                     "1 tbsp rice flour", "Juice of 1 lemon", "Oil for shallow frying", "Salt to taste"],
        steps=["Cut basa into fillets or fingers. Marinate with ginger-garlic paste, spices, lemon juice and salt for 20 minutes.",
               "Mix semolina and rice flour on a plate.",
               "Press each piece of fish into the semolina mix to coat well.",
               "Heat oil in a shallow pan over medium-high heat.",
               "Fry fish pieces 3-4 minutes per side until golden and crisp.",
               "Drain on paper towels and serve hot with lemon wedges."],
        prep_time_minutes=20, cook_time_minutes=10, difficulty="Easy", servings=3,
        tags=["fried", "indian", "starter"], product_tags=["vietnamese basa fish fillet", "basa"],
        search_keywords=["fish fry recipe", "crispy basa fry"],
    ),
    dict(
        title="Baked Snapper with Herbs", emoji="🌿", cuisine="Continental", category="seafood",
        description="Whole red snapper fillets baked with olive oil, garlic and fresh herbs until flaky.",
        ingredients=["2 red snapper fish fillets", "3 tbsp olive oil", "3 cloves garlic, sliced",
                     "1 lemon, sliced", "Fresh thyme and rosemary", "Salt & black pepper"],
        steps=["Preheat oven to 200C.",
               "Place snapper fillets on a lined baking tray.",
               "Drizzle with olive oil, season with salt and pepper.",
               "Scatter garlic slices, lemon slices, and herbs over the fish.",
               "Bake 15-18 minutes until the fish flakes easily with a fork.",
               "Serve immediately with the pan juices spooned over."],
        prep_time_minutes=10, cook_time_minutes=18, difficulty="Easy", servings=2,
        tags=["baked", "healthy", "herbs"], product_tags=["red snapper fish fillet", "snapper"],
        search_keywords=["baked snapper recipe", "herb roasted snapper"],
    ),
    dict(
        title="Sole Meuniere", emoji="🧈", cuisine="French", category="seafood",
        description="Delicate river sole fillets pan-fried in brown butter with lemon and parsley — a French bistro classic.",
        ingredients=["2 river sole fish fillets", "1/4 cup flour, seasoned with salt & pepper",
                     "4 tbsp butter", "1 lemon, juiced", "2 tbsp fresh parsley, chopped"],
        steps=["Dust sole fillets lightly in seasoned flour, shaking off excess.",
               "Heat 2 tbsp butter in a pan over medium heat until foaming.",
               "Fry the sole 2 minutes per side until golden. Remove and keep warm.",
               "Wipe the pan, add remaining butter and cook until nutty brown.",
               "Add lemon juice and parsley off the heat, swirl to combine.",
               "Pour the brown butter sauce over the sole and serve immediately."],
        prep_time_minutes=10, cook_time_minutes=10, difficulty="Medium", servings=2,
        tags=["french", "pan-fry", "classic"], product_tags=["river sole fish fillet", "sole"],
        search_keywords=["sole meuniere recipe", "pan fried sole"],
    ),
    dict(
        title="Crispy Tilapia Fish Fry", emoji="🍽️", cuisine="Indian", category="snack",
        description="Boneless tilapia fillets marinated in Indian spices and pan-fried to a crisp golden crust.",
        ingredients=["400g tilapia fish fillet", "1 tsp turmeric, 1 tsp red chilli powder",
                     "1 tbsp ginger-garlic paste", "2 tbsp rice flour", "Juice of 1 lemon",
                     "Oil for frying", "Salt to taste"],
        steps=["Marinate tilapia fillets with turmeric, chilli powder, ginger-garlic paste, lemon juice and salt for 15 minutes.",
               "Coat each fillet lightly in rice flour.",
               "Heat oil in a frying pan over medium-high heat.",
               "Shallow fry fillets 3 minutes per side until crisp and golden.",
               "Drain on paper towels and serve hot with onion rings and lemon."],
        prep_time_minutes=15, cook_time_minutes=8, difficulty="Easy", servings=3,
        tags=["fried", "indian", "quick"], product_tags=["tilapia fish fillet", "tilapia"],
        search_keywords=["tilapia fish fry recipe", "crispy tilapia"],
    ),
    dict(
        title="Whole Pomfret Fry", emoji="🐟", cuisine="Indian", category="snack",
        description="Whole white pomfret slashed, marinated in a coastal spice paste, and shallow-fried whole.",
        ingredients=["1 whole white pomfret, cleaned", "2 tbsp semolina", "1 tbsp Kashmiri chilli powder",
                     "1 tsp turmeric", "1 tbsp ginger-garlic paste", "Juice of 1 lime", "Oil for frying", "Salt to taste"],
        steps=["Make 2-3 deep diagonal slashes on both sides of the pomfret.",
               "Mix chilli powder, turmeric, ginger-garlic paste, lime juice and salt into a paste.",
               "Rub the paste all over the fish, including inside the slashes. Marinate 20 minutes.",
               "Coat the fish lightly in semolina.",
               "Shallow fry in hot oil 4-5 minutes per side until crisp and cooked through.",
               "Serve hot with lime wedges and sliced onions."],
        prep_time_minutes=20, cook_time_minutes=10, difficulty="Medium", servings=2,
        tags=["indian", "whole-fish", "coastal"], product_tags=["white pomfret whole", "pomfret"],
        search_keywords=["pomfret fry recipe", "whole fish fry"],
    ),
    dict(
        title="Pomfret Curry", emoji="🍛", cuisine="Indian", category="curry",
        description="White pomfret simmered in a coconut-based coastal curry with tamarind and curry leaves.",
        ingredients=["1 whole white pomfret, cut into pieces", "1 cup coconut milk", "1 onion, chopped",
                     "2 tomatoes, chopped", "1 tbsp tamarind pulp", "1 tsp turmeric, 1 tbsp chilli powder",
                     "Curry leaves, mustard seeds for tempering", "2 tbsp oil", "Salt to taste"],
        steps=["Marinate pomfret pieces with turmeric and salt for 10 minutes.",
               "Heat oil, temper mustard seeds and curry leaves.",
               "Add onions, saute until soft, then add tomatoes and cook until mushy.",
               "Add chilli powder and tamarind pulp, cook 2 minutes.",
               "Pour in coconut milk and bring to a gentle simmer.",
               "Add pomfret pieces, cover and cook 8-10 minutes until the fish is cooked through.",
               "Serve with steamed rice."],
        prep_time_minutes=15, cook_time_minutes=20, difficulty="Medium", servings=3,
        tags=["curry", "coastal", "coconut"], product_tags=["white pomfret whole", "pomfret"],
        search_keywords=["pomfret curry recipe", "coconut fish curry"],
    ),
    dict(
        title="Tuna Poke Bowl", emoji="🥗", cuisine="Japanese", category="seafood",
        description="Diced yellowfin tuna marinated in soy and sesame, served over rice with fresh vegetables.",
        ingredients=["250g yellowfin tuna ahi portions, cubed", "2 tbsp soy sauce", "1 tsp sesame oil",
                     "1 tsp rice vinegar", "2 cups cooked rice", "1/2 cucumber, sliced",
                     "1/4 cup edamame", "Sesame seeds"],
        steps=["Cube the tuna into bite-size pieces.",
               "Whisk soy sauce, sesame oil, and rice vinegar in a bowl.",
               "Toss the tuna gently in the dressing, let marinate 10 minutes in the fridge.",
               "Divide rice between bowls, top with marinated tuna.",
               "Arrange cucumber and edamame around the tuna.",
               "Sprinkle sesame seeds and serve chilled."],
        prep_time_minutes=15, cook_time_minutes=0, difficulty="Easy", servings=2,
        tags=["no-cook", "healthy", "japanese"], product_tags=["yellowfin tuna ahi portions", "edamame"],
        search_keywords=["tuna poke bowl recipe", "ahi tuna bowl"],
    ),
    dict(
        title="Garlic Butter Prawns", emoji="🧈", cuisine="Continental", category="seafood",
        description="Vannamei prawns sauteed fast in garlic butter — a five-minute, five-ingredient weeknight dinner.",
        ingredients=["500g vannamei white prawns, peeled & deveined", "4 tbsp butter", "5 cloves garlic, minced",
                     "1 tsp chilli flakes", "Juice of 1/2 lemon", "Fresh parsley, chopped"],
        steps=["Pat prawns completely dry.",
               "Melt butter in a wide pan over medium-high heat.",
               "Add garlic, cook 30 seconds until fragrant, don't let it brown.",
               "Add prawns in a single layer, cook 90 seconds without stirring.",
               "Flip prawns, add chilli flakes and lemon juice, cook 60-90 seconds more.",
               "Remove from heat once prawns turn pink and curl. Garnish with parsley and serve."],
        prep_time_minutes=5, cook_time_minutes=5, difficulty="Easy", servings=3,
        tags=["quick", "butter", "garlic"], product_tags=["vannamei white prawns", "prawns"],
        search_keywords=["garlic butter prawns recipe", "quick prawn dinner"],
    ),
    dict(
        title="Sashimi Salmon Platter", emoji="🍣", cuisine="Japanese", category="sushi",
        description="Thinly sliced sashimi-grade salmon served simply with wasabi, soy sauce and pickled ginger.",
        ingredients=["200g sashimi grade salmon block", "2 tbsp Kikkoman soy sauce",
                     "1 tbsp wasabi paste", "Pickled ginger", "1 sheet nori, cut into strips"],
        steps=["Chill the salmon block well before slicing — it slices much cleaner cold.",
               "Using a sharp knife, slice the salmon against the grain into 5mm thick pieces.",
               "Arrange the slices fanned out on a chilled plate.",
               "Garnish with nori strips and a small mound of pickled ginger.",
               "Serve with small dishes of soy sauce and wasabi on the side."],
        prep_time_minutes=15, cook_time_minutes=0, difficulty="Easy", servings=2,
        tags=["no-cook", "japanese", "raw"], product_tags=["sashimi grade salmon block", "wasabi paste"],
        search_keywords=["salmon sashimi recipe", "sashimi platter"],
    ),
    dict(
        title="Prawn Tempura", emoji="🍤", cuisine="Japanese", category="snack",
        description="Jumbo tiger prawns in a light, crispy tempura batter, served with a wasabi dipping sauce.",
        ingredients=["8 jumbo tiger prawns, peeled with tails on", "1 cup ice-cold sparkling water",
                     "1 cup flour", "1 egg yolk", "Oil for deep frying", "1 tsp wasabi paste for dipping"],
        steps=["Butterfly the prawns slightly so they stay straight when fried.",
               "Whisk egg yolk into ice-cold sparkling water, then fold in flour gently — a few lumps are fine.",
               "Heat oil to 180C in a deep pot.",
               "Hold prawns by the tail, dip in batter, and lower into the oil.",
               "Fry 2-3 minutes until pale gold and crisp. Do not overcrowd the pot.",
               "Drain on a rack and serve immediately with wasabi and soy dipping sauce."],
        prep_time_minutes=15, cook_time_minutes=10, difficulty="Medium", servings=2,
        tags=["fried", "japanese", "starter"], product_tags=["jumbo tiger prawns", "wasabi paste"],
        search_keywords=["prawn tempura recipe", "japanese fried prawns"],
    ),
    dict(
        title="Sweet Prawn Nigiri", emoji="🍣", cuisine="Japanese", category="sushi",
        description="Amaebi sweet prawns hand-pressed over vinegared sushi rice — a delicate, naturally sweet nigiri.",
        ingredients=["8 sweet prawns (amaebi), shelled", "1.5 cups cooked sushi rice",
                     "2 tbsp Japanese rice vinegar", "1 tsp sugar", "1/2 tsp salt", "Wasabi paste"],
        steps=["Mix rice vinegar, sugar and salt, fold gently through warm cooked rice, then let cool.",
               "Wet your hands to prevent sticking. Shape rice into small ovals, about 2 tbsp each.",
               "Dab a tiny amount of wasabi on top of each rice oval.",
               "Drape a sweet prawn over each rice oval, pressing gently to adhere.",
               "Serve immediately with soy sauce on the side."],
        prep_time_minutes=25, cook_time_minutes=0, difficulty="Medium", servings=2,
        tags=["sushi", "japanese", "no-cook"], product_tags=["sweet prawns", "japanese short-grain sushi rice"],
        search_keywords=["prawn nigiri recipe", "amaebi sushi"],
    ),
    dict(
        title="Miso Black Cod", emoji="🐟", cuisine="Japanese", category="seafood",
        description="Black cod marinated for days in a sweet miso glaze, then broiled until caramelized — the Nobu classic.",
        ingredients=["2 black cod fillets (headless)", "3 tbsp white miso paste", "2 tbsp mirin",
                     "2 tbsp sake or water", "2 tbsp sugar"],
        steps=["Whisk miso, mirin, sake and sugar together into a smooth marinade.",
               "Coat the black cod fillets thoroughly and place in a container.",
               "Marinate in the refrigerator for at least 24 hours, ideally 48.",
               "Preheat the broiler/grill to high. Wipe excess marinade off the fillets.",
               "Broil 6-8 minutes until deeply caramelized and just cooked through, watching closely so the sugars don't burn.",
               "Rest 2 minutes before serving."],
        prep_time_minutes=1440, cook_time_minutes=8, difficulty="Medium", servings=2,
        tags=["japanese", "premium", "marinated"], product_tags=["black cod headless", "shiro miso paste"],
        search_keywords=["miso black cod recipe", "nobu black cod"],
    ),
    dict(
        title="Vegetable Gyoza", emoji="🥟", cuisine="Japanese", category="snack",
        description="Pan-fried dumplings with a crisp golden base, filled with cabbage and mushrooms.",
        ingredients=["20 gyoza sheets", "2 cups cabbage, finely shredded", "1 cup shiitake mushrooms, minced",
                     "2 spring onions, chopped", "1 tbsp soy sauce", "1 tsp sesame oil", "2 tbsp oil for frying"],
        steps=["Salt the shredded cabbage, let sit 10 minutes, then squeeze out excess water.",
               "Mix cabbage, mushrooms, spring onion, soy sauce and sesame oil into a filling.",
               "Place a spoonful of filling in the center of each gyoza sheet, wet the edges, and pleat closed.",
               "Heat oil in a non-stick pan over medium heat, arrange gyoza flat-side down.",
               "Fry 2 minutes until the base is golden, then add a splash of water and cover to steam 4 minutes.",
               "Uncover and let the water evaporate to re-crisp the base. Serve with soy-vinegar dip."],
        prep_time_minutes=30, cook_time_minutes=8, difficulty="Medium", servings=4,
        tags=["japanese", "dumplings", "party"], product_tags=["gyoza sheet"],
        search_keywords=["vegetable gyoza recipe", "japanese dumplings"],
    ),
    dict(
        title="Ikura Don", emoji="🍚", cuisine="Japanese", category="seafood",
        description="A simple, luxurious rice bowl topped generously with glistening salmon roe and nori.",
        ingredients=["2 cups cooked sushi rice", "100g ikura (salmon roe)", "1 sheet nori, shredded",
                     "1 tsp rice vinegar", "Wasabi to serve"],
        steps=["Season the warm rice lightly with rice vinegar and let it cool slightly.",
               "Divide the rice between two bowls.",
               "Scatter shredded nori generously over the rice.",
               "Spoon the ikura on top, mounding it in the center.",
               "Serve immediately with a small dab of wasabi and soy sauce on the side."],
        prep_time_minutes=10, cook_time_minutes=0, difficulty="Easy", servings=2,
        tags=["japanese", "no-cook", "premium"], product_tags=["ikura salmon roe", "nori"],
        search_keywords=["ikura don recipe", "salmon roe rice bowl"],
    ),
    dict(
        title="California Roll", emoji="🍣", cuisine="Japanese", category="sushi",
        description="Inside-out sushi roll with crab, avocado and cucumber, finished with a coat of tobiko.",
        ingredients=["2 cups cooked sushi rice", "2 nori sheets", "150g crab meat (or imitation crab), flaked",
                     "1 avocado, sliced", "1/2 cucumber, julienned", "2 tbsp tobiko (orange flying fish roe)",
                     "Japanese rice vinegar for seasoning"],
        steps=["Season the sushi rice with a little rice vinegar and let it cool.",
               "Place a nori sheet on a bamboo mat, rice-side down, and press an even layer of rice over it.",
               "Flip so the rice faces down onto the mat, then arrange crab, avocado and cucumber along the center.",
               "Using the mat, roll tightly into a cylinder.",
               "Roll the outside of the sushi roll in tobiko to coat.",
               "Slice into 8 pieces with a wet, sharp knife and serve with soy sauce."],
        prep_time_minutes=35, cook_time_minutes=0, difficulty="Medium", servings=2,
        tags=["sushi", "japanese", "no-cook"], product_tags=["tobiko orange flying fish roe", "premium roasted nori"],
        search_keywords=["california roll recipe", "sushi roll"],
    ),
    dict(
        title="Dashi Miso Soup", emoji="🍜", cuisine="Japanese", category="soup",
        description="The everyday Japanese soup — a light bonito dashi broth stirred through with white miso.",
        ingredients=["4 cups water", "2 tsp hondashi instant dashi granules", "3 tbsp white miso paste",
                     "1/2 block silken tofu, cubed", "1 sheet nori, torn", "1 spring onion, sliced"],
        steps=["Bring water to a simmer, stir in hondashi granules to make the dashi stock.",
               "Ladle a little hot dashi into a bowl and whisk the miso paste into it until smooth.",
               "Return the miso mixture to the pot, stirring gently — do not let it boil once the miso is added.",
               "Add the tofu cubes and warm through for 1-2 minutes.",
               "Ladle into bowls, garnish with nori and spring onion, and serve immediately."],
        prep_time_minutes=5, cook_time_minutes=10, difficulty="Easy", servings=4,
        tags=["japanese", "soup", "quick"], product_tags=["hondashi instant dashi", "shiro miso paste"],
        search_keywords=["miso soup recipe", "dashi soup"],
    ),
    dict(
        title="Edamame with Sea Salt", emoji="🫛", cuisine="Japanese", category="snack",
        description="Steamed edamame pods finished with flaky sea salt — the simplest Japanese izakaya starter.",
        ingredients=["300g edamame (green soybeans with pod)", "1 tsp sea salt", "1 tsp sesame oil (optional)"],
        steps=["Bring a pot of salted water to a boil.",
               "Add the edamame pods and boil for 4-5 minutes until tender.",
               "Drain well and toss with sea salt while still hot.",
               "Drizzle with a touch of sesame oil if using, and serve warm."],
        prep_time_minutes=2, cook_time_minutes=5, difficulty="Easy", servings=4,
        tags=["japanese", "snack", "vegetarian"], product_tags=["edamame green soybeans"],
        search_keywords=["edamame recipe", "steamed edamame"],
    ),
    dict(
        title="Kampachi Sashimi", emoji="🍣", cuisine="Japanese", category="sushi",
        description="Silky kampachi (amberjack) sliced thin and served simply to let its buttery flavor shine.",
        ingredients=["200g kampachi fish fillet (amberjack)", "2 tbsp soy sauce", "1 tsp yuzu or lemon juice",
                     "Thinly sliced spring onion", "Wasabi to serve"],
        steps=["Chill the kampachi thoroughly before slicing.",
               "Slice against the grain into thin, even pieces using a sharp knife.",
               "Arrange on a chilled plate, slightly overlapping.",
               "Mix soy sauce with a dash of yuzu or lemon juice for dipping.",
               "Garnish with spring onion and serve immediately with wasabi."],
        prep_time_minutes=10, cook_time_minutes=0, difficulty="Easy", servings=2,
        tags=["japanese", "raw", "no-cook"], product_tags=["kampachi fish fillet amberjack"],
        search_keywords=["kampachi sashimi recipe", "amberjack sashimi"],
    ),
    dict(
        title="Grilled Seabass with Ponzu", emoji="🔥", cuisine="Japanese", category="grilled",
        description="Whole seabass fillets grilled simply and finished with a citrusy ponzu drizzle.",
        ingredients=["2 bethki (Indian seabass) fillets", "2 tbsp Japanese rice vinegar", "2 tbsp soy sauce",
                     "1 tsp yuzu or lemon juice", "1 tbsp oil", "Grated daikon (optional)"],
        steps=["Whisk rice vinegar, soy sauce and yuzu/lemon juice together to make the ponzu.",
               "Rub the seabass fillets with oil and season lightly with salt.",
               "Preheat a grill or grill pan to high heat.",
               "Grill the fillets skin-side down for 4 minutes, then flip for 3 minutes until just cooked through.",
               "Plate the fish and drizzle generously with the ponzu sauce.",
               "Top with grated daikon if using, and serve immediately."],
        prep_time_minutes=10, cook_time_minutes=8, difficulty="Medium", servings=2,
        tags=["grilled", "japanese", "healthy"], product_tags=["bethki fish fillet seabass", "japanese rice vinegar"],
        search_keywords=["grilled seabass recipe", "ponzu fish"],
    ),
    dict(
        title="Grilled Canadian Lobster Tail", emoji="🦞", cuisine="Continental", category="grilled",
        description="Butterflied Canadian lobster tail brushed with garlic butter and grilled until just opaque.",
        ingredients=["2 Canadian lobster tails", "4 tbsp butter, melted", "2 cloves garlic, minced",
                     "1 tbsp lemon juice", "1 tbsp fresh parsley, chopped"],
        steps=["Using kitchen shears, cut through the top shell of each lobster tail lengthwise.",
               "Gently pull the meat up and rest it on top of the shell, keeping it attached at the base.",
               "Mix melted butter, garlic and lemon juice.",
               "Brush the lobster meat generously with the garlic butter.",
               "Grill flesh-side up over medium-high heat for 6-8 minutes until opaque and firm.",
               "Brush with remaining butter, garnish with parsley, and serve hot."],
        prep_time_minutes=10, cook_time_minutes=8, difficulty="Medium", servings=2,
        tags=["grilled", "premium", "date-night"], product_tags=["canadian lobster tail", "lobster tail"],
        search_keywords=["grilled lobster tail recipe", "butterflied lobster"],
    ),
    dict(
        title="Grilled Octopus Salad", emoji="🐙", cuisine="Mediterranean", category="grilled",
        description="Tender octopus, boiled then chargrilled for smoky edges, tossed with olive oil, lemon and herbs.",
        ingredients=["1 whole octopus, cleaned", "1 lemon, juiced", "3 tbsp olive oil", "2 cloves garlic, minced",
                     "1 tbsp fresh oregano or parsley", "Salt & pepper"],
        steps=["Simmer the octopus in a pot of water for 40-45 minutes until fork-tender.",
               "Drain and let cool slightly, then pat dry.",
               "Cut into large pieces and toss with a little olive oil.",
               "Grill over high heat for 3-4 minutes per side until charred and smoky.",
               "Whisk remaining olive oil, lemon juice, garlic and herbs into a dressing.",
               "Toss the grilled octopus in the dressing and serve warm or at room temperature."],
        prep_time_minutes=10, cook_time_minutes=50, difficulty="Medium", servings=3,
        tags=["grilled", "mediterranean", "salad"], product_tags=["octopus whole", "octopus"],
        search_keywords=["grilled octopus recipe", "octopus salad"],
    ),
    dict(
        title="Grilled Lamb Rack", emoji="🍖", cuisine="Continental", category="grilled",
        description="New Zealand lamb rack, herb-crusted and grilled to a perfect pink center.",
        ingredients=["1 lamb rack (cap on), frenched", "2 tbsp olive oil", "2 cloves garlic, minced",
                     "1 tbsp fresh rosemary, chopped", "1 tsp fresh thyme", "Salt & black pepper"],
        steps=["Bring the lamb rack to room temperature and pat dry.",
               "Mix olive oil, garlic, rosemary and thyme into a paste, rub all over the lamb.",
               "Season generously with salt and pepper.",
               "Preheat a grill to medium-high heat.",
               "Grill the rack, turning occasionally, for 15-18 minutes for medium-rare (internal temp 55C).",
               "Rest for 5-10 minutes before slicing between the bones and serving."],
        prep_time_minutes=10, cook_time_minutes=18, difficulty="Medium", servings=2,
        tags=["grilled", "premium", "dinner-party"], product_tags=["lamb rack cap on", "lamb rack"],
        search_keywords=["grilled lamb rack recipe", "herb crusted lamb"],
    ),
    dict(
        title="Grilled Pork Chops", emoji="🍖", cuisine="Continental", category="grilled",
        description="Bone-in pork loin chops brined briefly then grilled for a juicy, well-charred result.",
        ingredients=["2 pork loin chops (bone-in)", "2 tbsp olive oil", "1 tsp smoked paprika",
                     "1 tsp garlic powder", "Salt & pepper", "Lemon wedges to serve"],
        steps=["Pat the pork chops dry and rub with olive oil.",
               "Season generously with smoked paprika, garlic powder, salt and pepper.",
               "Let sit at room temperature for 15 minutes before grilling.",
               "Preheat a grill or grill pan to medium-high heat.",
               "Grill 5-6 minutes per side until the internal temperature reaches 63C.",
               "Rest 5 minutes before serving with lemon wedges."],
        prep_time_minutes=15, cook_time_minutes=12, difficulty="Easy", servings=2,
        tags=["grilled", "quick", "weeknight"], product_tags=["pork loin chops"],
        search_keywords=["grilled pork chops recipe", "bone in pork chops"],
    ),
    dict(
        title="Singapore Chilli Crab", emoji="🦀", cuisine="Asian", category="curry",
        description="Whole mud crab simmered in a sweet, spicy, tomato-egg sauce — Singapore's most famous seafood dish.",
        ingredients=["1 whole mud crab (live), cleaned and cut into pieces", "3 tbsp chilli sauce", "2 tbsp tomato ketchup",
                     "1 tbsp soy sauce", "1 tbsp sugar", "3 cloves garlic, minced", "1 tbsp ginger, minced",
                     "1 egg, beaten", "2 tbsp cornstarch mixed with water", "2 tbsp oil"],
        steps=["Heat oil in a wok over high heat, stir-fry garlic and ginger until fragrant.",
               "Add the crab pieces and stir-fry 2-3 minutes until the shells turn red.",
               "Add chilli sauce, ketchup, soy sauce and sugar with a splash of water. Stir to coat the crab.",
               "Cover and cook 8-10 minutes, stirring occasionally, until the crab is cooked through.",
               "Stir in the cornstarch slurry to thicken the sauce.",
               "Drizzle in the beaten egg while stirring, so it forms silky ribbons through the sauce.",
               "Serve hot with steamed buns or rice to mop up the sauce."],
        prep_time_minutes=15, cook_time_minutes=20, difficulty="Hard", servings=3,
        tags=["curry", "asian", "premium"], product_tags=["mud crab live", "whole rock crab"],
        search_keywords=["singapore chilli crab recipe", "chilli crab"],
    ),
    dict(
        title="Lamb Curry", emoji="🍛", cuisine="Indian", category="curry",
        description="Slow-simmered lamb shank curry in a deeply spiced onion-tomato gravy, falling off the bone.",
        ingredients=["1 lamb shank", "2 onions, sliced", "2 tomatoes, pureed", "1 tbsp ginger-garlic paste",
                     "2 tsp garam masala, 1 tsp turmeric, 1 tbsp chilli powder, 1 tsp cumin powder",
                     "3 tbsp oil or ghee", "Fresh coriander to garnish", "Salt to taste"],
        steps=["Heat oil in a heavy pot, fry onions until deep golden brown (12-15 mins).",
               "Add ginger-garlic paste, cook 2 minutes.",
               "Add the lamb shank, sear on all sides for 5 minutes.",
               "Add tomato puree and all the dry spices, cook until the oil separates.",
               "Add enough water to cover the shank, bring to a boil, then reduce to a low simmer.",
               "Cover and cook 90 minutes to 2 hours until the meat is fork-tender, topping up water as needed.",
               "Garnish with fresh coriander and serve with rice or naan."],
        prep_time_minutes=15, cook_time_minutes=110, difficulty="Hard", servings=3,
        tags=["curry", "indian", "slow-cook"], product_tags=["lamb shank"],
        search_keywords=["lamb curry recipe", "lamb shank curry"],
    ),
    dict(
        title="Salmon Head Curry", emoji="🍛", cuisine="Indian", category="curry",
        description="An economical, deeply flavorful coastal curry made from salmon heads simmered with coconut and tamarind.",
        ingredients=["2 salmon heads (gutted), cut into pieces", "1 cup coconut milk", "1 onion, chopped",
                     "2 tomatoes, chopped", "1 tbsp tamarind pulp", "1 tsp turmeric, 1 tbsp chilli powder",
                     "Curry leaves, mustard seeds for tempering", "2 tbsp oil", "Salt to taste"],
        steps=["Clean the salmon head pieces well and marinate with turmeric and salt for 10 minutes.",
               "Heat oil, temper mustard seeds and curry leaves.",
               "Saute onion until soft, add tomatoes and cook until mushy.",
               "Add chilli powder and tamarind pulp, cook 2 minutes.",
               "Pour in coconut milk, bring to a simmer.",
               "Add the salmon head pieces, cover and simmer 15-18 minutes until fully cooked.",
               "Serve hot with steamed rice."],
        prep_time_minutes=15, cook_time_minutes=25, difficulty="Medium", servings=3,
        tags=["curry", "coastal", "economical"], product_tags=["salmon head gutted"],
        search_keywords=["salmon head curry recipe", "fish head curry"],
    ),
    dict(
        title="Lobster Bisque", emoji="🥣", cuisine="French", category="soup",
        description="A rich, silky French soup made from lobster shells and stock, finished with cream and a splash of brandy.",
        ingredients=["2 lobster tails (shells reserved)", "2 tbsp butter", "1 onion, chopped", "1 carrot, chopped",
                     "2 tbsp tomato paste", "1/4 cup brandy (optional)", "3 cups fish or seafood stock", "1/2 cup cream"],
        steps=["Remove lobster meat from the tails, roughly chop, and set aside. Reserve the shells.",
               "Melt butter in a pot, saute onion and carrot until soft.",
               "Add the lobster shells and tomato paste, cook 3-4 minutes.",
               "Add brandy if using and let it bubble for a minute.",
               "Pour in the stock, bring to a simmer, and cook 20 minutes to extract flavor from the shells.",
               "Strain the soup, discarding the shells and vegetables, then return the liquid to the pot.",
               "Stir in cream and the chopped lobster meat, warm through gently, and season to taste before serving."],
        prep_time_minutes=15, cook_time_minutes=25, difficulty="Medium", servings=3,
        tags=["soup", "french", "premium"], product_tags=["lobster tail", "canadian lobster tail"],
        search_keywords=["lobster bisque recipe", "lobster soup"],
    ),
    dict(
        title="Wonton Soup", emoji="🥟", cuisine="Chinese", category="soup",
        description="Delicate pork-filled wontons simmered in a light, savory broth with spring onion.",
        ingredients=["20 wonton sheets (white)", "200g pork collar, minced", "1 tsp ginger, grated",
                     "1 tbsp soy sauce", "1 tsp sesame oil", "4 cups chicken or pork stock",
                     "2 spring onions, sliced"],
        steps=["Mix minced pork, ginger, soy sauce and sesame oil into a filling.",
               "Place a small spoonful of filling in the center of each wonton sheet.",
               "Wet the edges, fold into a triangle, then bring the two corners together to seal.",
               "Bring a pot of water to a boil and cook the wontons for 4-5 minutes until they float.",
               "Meanwhile, heat the stock in a separate pot and season to taste.",
               "Divide the cooked wontons between bowls, ladle over hot stock, and garnish with spring onion."],
        prep_time_minutes=30, cook_time_minutes=15, difficulty="Medium", servings=4,
        tags=["soup", "chinese", "dumplings"], product_tags=["wonton sheet white", "pork collar"],
        search_keywords=["wonton soup recipe", "pork wonton"],
    ),
    dict(
        title="Crispy Fried Wontons", emoji="🥟", cuisine="Chinese", category="snack",
        description="Deep-fried pork wontons with a crunchy shell — a popular dim sum starter with sweet chilli dip.",
        ingredients=["20 wonton sheets (yellow)", "200g pork collar, minced", "2 spring onions, chopped",
                     "1 tbsp soy sauce", "1 tsp sesame oil", "Oil for deep frying", "Sweet chilli sauce to serve"],
        steps=["Mix minced pork, spring onion, soy sauce and sesame oil into a filling.",
               "Place a small spoonful in the center of each wonton sheet, wet the edges, and fold into a triangle or purse shape, sealing well.",
               "Heat oil to 180C in a deep pan.",
               "Fry the wontons in batches for 3-4 minutes until golden and crisp.",
               "Drain on paper towels and serve hot with sweet chilli sauce."],
        prep_time_minutes=25, cook_time_minutes=12, difficulty="Easy", servings=4,
        tags=["fried", "chinese", "party"], product_tags=["wonton sheet yellow", "pork collar"],
        search_keywords=["fried wonton recipe", "crispy wontons"],
    ),
    dict(
        title="Vegetable Spring Rolls", emoji="🌯", cuisine="Vietnamese", category="snack",
        description="Crisp fried spring rolls packed with cabbage, carrot and glass noodles — a Vietnamese-Thai party favorite.",
        ingredients=["16 spring roll sheets", "2 cups cabbage, shredded", "1 carrot, julienned",
                     "1/2 cup glass noodles, soaked and chopped", "1 tbsp soy sauce", "Oil for deep frying"],
        steps=["Mix cabbage, carrot, glass noodles and soy sauce into a filling.",
               "Place a spoonful of filling along one edge of a spring roll sheet.",
               "Roll tightly, folding in the sides halfway, and seal the edge with a little water.",
               "Heat oil to 180C in a deep pan.",
               "Fry the rolls in batches for 3-4 minutes until golden and crisp.",
               "Drain on paper towels and serve hot with sweet chilli or nuoc cham dipping sauce."],
        prep_time_minutes=25, cook_time_minutes=12, difficulty="Medium", servings=4,
        tags=["fried", "vietnamese", "party"], product_tags=["spring roll sheet"],
        search_keywords=["spring rolls recipe", "vegetable spring rolls"],
    ),
    dict(
        title="Baklava", emoji="🍯", cuisine="Greek", category="snack",
        description="Layers of crisp filo pastry and spiced walnuts, soaked in honey syrup — a Greek pastry showstopper.",
        ingredients=["1 pack filo pastry sheets", "2 cups walnuts, finely chopped", "1 tsp cinnamon",
                     "200g butter, melted", "1 cup honey", "1/2 cup sugar", "1/2 cup water", "1 tsp lemon juice"],
        steps=["Preheat oven to 160C. Mix walnuts with cinnamon.",
               "Brush a baking tray with melted butter, layer in 8 filo sheets, brushing each with butter.",
               "Spread half the walnut mixture over the pastry, then repeat with 6 more buttered filo layers.",
               "Add the remaining walnuts, then top with the final 8 buttered filo layers.",
               "Cut into diamond shapes before baking. Bake 40-45 minutes until deep golden.",
               "Meanwhile, simmer honey, sugar, water and lemon juice for 5 minutes to make the syrup.",
               "Pour the warm syrup evenly over the hot baklava as soon as it comes out of the oven. Let it soak for a few hours before serving."],
        prep_time_minutes=30, cook_time_minutes=45, difficulty="Hard", servings=12,
        tags=["greek", "dessert", "party"], product_tags=["filo pastry sheets"],
        search_keywords=["baklava recipe", "filo pastry dessert"],
    ),
    dict(
        title="Kataifi Prawn Rolls", emoji="🍤", cuisine="Mediterranean", category="snack",
        description="Jumbo prawns wrapped in shredded kataifi pastry and fried until golden and crackly.",
        ingredients=["12 jumbo tiger prawns, peeled with tails on", "200g kataifi shredded pastry",
                     "2 tbsp melted butter", "Salt & pepper", "Oil for frying"],
        steps=["Season the prawns with salt and pepper.",
               "Take a small handful of kataifi pastry and wrap it around each prawn, leaving the tail exposed.",
               "Brush the wrapped prawns lightly with melted butter to help them crisp evenly.",
               "Heat oil in a pan over medium-high heat.",
               "Fry the wrapped prawns 2-3 minutes per side, turning gently, until the pastry is golden and crisp.",
               "Drain on paper towels and serve hot with a dipping sauce of choice."],
        prep_time_minutes=20, cook_time_minutes=10, difficulty="Medium", servings=4,
        tags=["fried", "mediterranean", "party"], product_tags=["kataifi shredded pastry", "jumbo tiger prawns"],
        search_keywords=["kataifi prawns recipe", "shredded pastry prawns"],
    ),
    dict(
        title="Squid Ink Pasta", emoji="🍝", cuisine="Italian", category="noodles",
        description="Squid tubes sliced into rings and tossed through garlic-chilli pasta with a briny, deep-sea flavor.",
        ingredients=["300g squid tube (IQF), sliced into rings", "300g spaghetti", "4 cloves garlic, sliced",
                     "1 red chilli, sliced", "1/4 cup olive oil", "1/4 cup white wine", "Fresh parsley, chopped"],
        steps=["Cook spaghetti in salted boiling water until al dente. Reserve a cup of pasta water.",
               "Heat olive oil in a large pan, saute garlic and chilli until fragrant.",
               "Add squid rings and cook on high heat for 60-90 seconds only — do not overcook or they turn rubbery.",
               "Add white wine and let it bubble for a minute.",
               "Toss in the drained pasta with a splash of pasta water to loosen the sauce.",
               "Finish with parsley and serve immediately."],
        prep_time_minutes=10, cook_time_minutes=15, difficulty="Medium", servings=3,
        tags=["pasta", "italian", "seafood"], product_tags=["squid tube", "squid"],
        search_keywords=["squid pasta recipe", "seafood pasta"],
    ),
    dict(
        title="Yaki Udon with Duck", emoji="🍜", cuisine="Japanese", category="noodles",
        description="Stir-fried udon noodles tossed with smoked duck breast, cabbage and a savory soy glaze.",
        ingredients=["300g udon noodles", "150g smoked duck breast, sliced", "2 cups cabbage, shredded",
                     "1 carrot, julienned", "3 tbsp Kikkoman soy sauce", "1 tbsp mirin", "2 tbsp oil"],
        steps=["Cook udon noodles per packet instructions, drain and set aside.",
               "Heat oil in a wok over high heat, stir-fry cabbage and carrot for 2 minutes.",
               "Add the sliced smoked duck breast and toss to warm through for 1-2 minutes.",
               "Add the udon noodles, soy sauce and mirin, tossing everything together for 2 minutes.",
               "Serve immediately while hot."],
        prep_time_minutes=10, cook_time_minutes=12, difficulty="Medium", servings=2,
        tags=["noodles", "japanese", "quick"], product_tags=["smoked duck breast", "kikkoman soy sauce"],
        search_keywords=["yaki udon recipe", "duck noodles"],
    ),
    dict(
        title="Teriyaki Sauce", emoji="🥄", cuisine="Japanese", category="sauce",
        description="A quick homemade teriyaki glaze built on Kikkoman soy sauce and mirin — use on salmon, duck or prawns.",
        ingredients=["1/4 cup Kikkoman koikuchi soy sauce", "1/4 cup hon mirin", "2 tbsp sugar", "1 tsp cornstarch mixed with 1 tbsp water"],
        steps=["Combine soy sauce, mirin and sugar in a small saucepan.",
               "Bring to a gentle simmer over medium heat, stirring until the sugar dissolves.",
               "Stir in the cornstarch slurry and simmer 1-2 minutes until the sauce thickens enough to coat a spoon.",
               "Remove from heat and let cool slightly before using as a glaze or dipping sauce."],
        prep_time_minutes=2, cook_time_minutes=8, difficulty="Easy", servings=4,
        tags=["sauce", "japanese", "quick"], product_tags=["kikkoman koikuchi soy sauce", "hon mirin"],
        search_keywords=["teriyaki sauce recipe", "homemade teriyaki glaze"],
    ),
    dict(
        title="Ponzu Dipping Sauce", emoji="🍋", cuisine="Japanese", category="sauce",
        description="A bright, citrusy soy-vinegar dipping sauce for sashimi, grilled fish or dumplings.",
        ingredients=["3 tbsp Kikkoman soy sauce", "2 tbsp Japanese rice vinegar", "1 tbsp lemon or yuzu juice",
                     "1 tsp mirin", "A few flakes of bonito (optional)"],
        steps=["Whisk soy sauce, rice vinegar, lemon juice and mirin together in a small bowl.",
               "Add bonito flakes if using, and let the sauce infuse for 5-10 minutes.",
               "Strain if bonito was used, and serve as a dipping sauce alongside sashimi, gyoza or grilled fish."],
        prep_time_minutes=10, cook_time_minutes=0, difficulty="Easy", servings=4,
        tags=["sauce", "japanese", "no-cook"], product_tags=["japanese rice vinegar", "kikkoman soy sauce"],
        search_keywords=["ponzu sauce recipe", "citrus soy sauce"],
    ),
    dict(
        title="Wasabi Mayo Dip", emoji="🌶️", cuisine="Japanese", category="sauce",
        description="Creamy Kewpie mayonnaise spiked with wasabi — the classic dip for tempura, sushi or fries.",
        ingredients=["1/2 cup Kewpie Japanese mayonnaise", "1 tbsp wasabi paste", "1 tsp rice vinegar", "1 tsp soy sauce"],
        steps=["Whisk Kewpie mayonnaise, wasabi paste, rice vinegar and soy sauce together until smooth.",
               "Taste and add more wasabi for extra heat if desired.",
               "Chill for 10 minutes before serving alongside tempura, sushi or crispy fried snacks."],
        prep_time_minutes=5, cook_time_minutes=0, difficulty="Easy", servings=6,
        tags=["sauce", "japanese", "no-cook"], product_tags=["kewpie japanese mayonnaise", "wasabi paste"],
        search_keywords=["wasabi mayo recipe", "spicy mayo dip"],
    ),
    dict(
        title="Duck Confit", emoji="🦆", cuisine="French", category="roast",
        description="Duck legs slow-cooked until meltingly tender, then crisped — the classic French bistro preparation.",
        ingredients=["4 duck legs", "2 tbsp coarse salt", "4 cloves garlic, crushed", "4 sprigs thyme",
                     "2 bay leaves", "2 cups duck fat or oil (enough to submerge the legs)"],
        steps=["Rub the duck legs with salt, garlic, thyme and bay leaves. Cover and refrigerate for at least 8 hours, ideally overnight.",
               "Rinse off the salt cure and pat the legs completely dry.",
               "Preheat the oven to 150C. Submerge the duck legs in duck fat or oil in a deep oven-safe dish.",
               "Cook in the oven for 2.5-3 hours until the meat is fork-tender.",
               "To serve, remove the legs from the fat and crisp the skin in a hot pan for 3-4 minutes per side.",
               "Serve with roasted potatoes or a simple green salad."],
        prep_time_minutes=480, cook_time_minutes=180, difficulty="Hard", servings=4,
        tags=["french", "slow-cook", "premium"], product_tags=["duck legs"],
        search_keywords=["duck confit recipe", "french duck legs"],
    ),
    dict(
        title="Pan-Seared Duck Breast", emoji="🦆", cuisine="French", category="seafood",
        description="Raw duck breast scored and seared skin-side down until the fat renders into a crisp, glassy crust.",
        ingredients=["2 raw duck breasts", "Salt & black pepper", "1 tsp fresh thyme"],
        steps=["Score the duck skin in a crosshatch pattern, being careful not to cut into the meat.",
               "Season both sides generously with salt and pepper.",
               "Place skin-side down in a cold pan, then set over medium heat — this renders the fat slowly for maximum crispness.",
               "Cook 8-10 minutes until the skin is deep golden and most of the fat has rendered, spooning off excess fat as needed.",
               "Flip and cook the flesh side for 3-4 minutes for medium-rare.",
               "Rest 5 minutes before slicing and serving."],
        prep_time_minutes=5, cook_time_minutes=15, difficulty="Medium", servings=2,
        tags=["french", "seared", "premium"], product_tags=["raw duck breast"],
        search_keywords=["pan seared duck breast recipe", "crispy duck skin"],
    ),
    dict(
        title="Roast Whole Turkey", emoji="🦃", cuisine="Continental", category="roast",
        description="A classic whole roast turkey, butter-basted and roasted low and slow for a juicy, golden centerpiece.",
        ingredients=["1 whole turkey (Butterball)", "200g butter, softened", "2 lemons, halved",
                     "1 head garlic, halved", "Fresh rosemary and thyme", "Salt & black pepper"],
        steps=["Preheat oven to 160C. Pat the turkey completely dry inside and out.",
               "Stuff the cavity with lemon halves, garlic and herbs.",
               "Rub the entire turkey generously with softened butter, salt and pepper.",
               "Roast, basting every 30-40 minutes, allowing roughly 20 minutes per kg.",
               "The turkey is done when a thermometer in the thickest part of the thigh reads 74C.",
               "Rest for at least 20-30 minutes before carving to keep the meat juicy."],
        prep_time_minutes=30, cook_time_minutes=180, difficulty="Hard", servings=8,
        tags=["roast", "festive", "centerpiece"], product_tags=["whole turkey butterball"],
        search_keywords=["roast turkey recipe", "whole turkey christmas"],
    ),
]


def _redact_host(url: str) -> str:
    """Never print a connection string with embedded credentials — show only the host."""
    return re.sub(r"://[^@]+@", "://***:***@", url)


def main() -> None:
    client = MongoClient(MONGODB_URL)
    db = client[DATABASE_NAME]

    all_rows = MIGRATED + NEW_BATCH
    print(f"Seeding {len(all_rows)} recipes into '{DATABASE_NAME}' at {_redact_host(MONGODB_URL)} ...")

    result = recipe_service.admin_bulk_import_recipes(db, all_rows)
    data = result["data"]
    print(f"Created: {data['created']}")
    print(f"Skipped: {data['skipped']}")
    if data["errors"]:
        print("Skip reasons:")
        for e in data["errors"]:
            print(f"  row {e['row']}: {e['reason']}")

    total_now = db.recipes.count_documents({})
    print(f"Total recipes in collection now: {total_now}")
    client.close()


if __name__ == "__main__":
    main()
