export const ROUTES = {
  HOME: '/',
  PRODUCTS: '/products',
  PRODUCT_DETAIL: '/products/:slug',
  CART: '/cart',
  CHECKOUT: '/checkout',
  WISHLIST: '/wishlist',
  ORDERS: '/orders',
  ORDER_DETAIL: '/orders/:id',
  PROFILE: '/profile',
  REFERRAL: '/referral',
  BUNDLES: '/bundles',
  LOYALTY: '/loyalty',
  FLASH_SALES: '/flash-sales',
  SUBSCRIPTIONS: '/subscriptions',
  RECIPES: '/recipes',
  JAPANESE_GROCERY: '/japanese-grocery',
  ABOUT: '/about',
  TRACK_ORDER: '/track-order',
  BULK_ORDER: '/bulk-order',
  DRIVER: '/driver',
  BUSINESS_SOLUTIONS: '/business-solutions',
  AUTH: {
    LOGIN: '/auth/login',
    REGISTER: '/auth/register',
    FORGOT_PASSWORD: '/auth/forgot-password',
    RESET_PASSWORD: '/auth/reset-password',
  },
  ADMIN: {
    LOGIN: '/admin/login',
    DASHBOARD: '/admin',
    PRODUCTS: '/admin/products',
    ORDERS: '/admin/orders',
    CUSTOMERS: '/admin/customers',
    CATEGORIES: '/admin/categories',
    BANNERS: '/admin/banners',
    COUPONS: '/admin/coupons',
    ANALYTICS: '/admin/analytics',
    BUNDLES: '/admin/bundles',
    SETTINGS: '/admin/settings',
    INVENTORY: '/admin/inventory',
    BULK_ORDERS: '/admin/bulk-orders',
    GIFT_CARDS: '/admin/gift-cards',
    DRIVERS: '/admin/drivers',
    USERS: '/admin/users',
  },
} as const
